Throw a UriNotFoundException if the URI is not part of the message
Rollbar: https://rollbar.com/dxw/tna-caselaw-ingester/items/23/

```
AttributeError: 'NoneType' object has no attribute 'replace' (Most recent call last)
File /var/task/lambda_function.py line 154 in handler args locals
uri = extract_uri(metadata)
File /var/task/lambda_function.py line 43 in extract_uri args locals
'return metadata["parameters"]["PARSER"]["uri"]....s://caselaw.nationalarchives.gov.uk/id/\', \'\')'
```

If the metadata JSON doesn't contain any reference to a uri, the lambda is
erroring without throwing a UriNotFoundException, because it can't perform a
`replace` on a non-existent object. Move the UriNotFoundException up into the
`extract_uri` method to catch this error.