Upgrade localstack to 3.5.0
We were having issues with errors on pdf-converter where the v2 AWS API
was trying to be used but was causing errors. Upgrading fixed them.

Something like:

localstack.aws.protocol.parser.ProtocolParserError: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs)